all: 1_array_construct 2_array_access
1_array_construct: 1_array_construct.cpp
	g++ -g -o 1_array_construct 1_array_construct.cpp

2_array_access: 2_array_access.cpp
	g++ -g -o 2_array_access 2_array_access.cpp