all: 1_array_construct 2_array_access 3_array_undefined_access
1_array_construct: 1_array_construct.cpp
	g++ -g -o 1_array_construct 1_array_construct.cpp

2_array_access: 2_array_access.cpp
	g++ -g -o 2_array_access 2_array_access.cpp

3_array_undefined_access: 3_array_undefined_access.cpp
	g++ -g -o 3_array_undefined_access 3_array_undefined_access.cpp